### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by menems** [menems/koa-66#1]
## task list
- [x] comments
- [ ] more Test (async missing)
- [x] Docs
- [x] Consolidate input test
- [x] Add multiple middleware support
- [x] 405 Method Not Allowed and 501 Not Implemented.
